"""Initial migration

Revision ID: 952c95adcfc4
Revises: 
Create Date: 2025-03-18 01:43:12.913193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952c95adcfc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_claim_user_id', 'user', ['user_id'], ['id'])  # Add a name here
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
